### ISSUE TITLE
Правила

### ISSUE THREAD

**Issue by igorkamyshev** [solid-soda/tslint-config#1]
@Uncleseneca Я не совсем понял, какие правила тут используются. Вроде договаривались взять взять конфиг из рабочего проекта для одной благотворительной организации (бэк) и вынести сюда. Но я попробовал поставить и там совсем что-то другое.

Если будет время, приведи, пожалуйста, к тому конфигу.

**Comment by Uncleseneca** [comment]
@igorkamyshev  обновил конфиг!

**Comment by igorkamyshev** [comment]
@Uncleseneca тер-индент нужна зависимостью — https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/terIndentRule.md

**Comment by Uncleseneca** [comment]
@igorkamyshev готово!
