### ISSUE TITLE
Правило для импортов

### ISSUE THREAD

**Issue by igorkamyshev** [solid-soda/tslint-config#2]
@Uncleseneca давай добавим правило, чтобы импорты были сначала из библиотек, а потом из проекта?

https://www.npmjs.com/package/tslint-origin-ordered-imports-rule

**Comment by igorkamyshev** [comment]
Только, кажется, нам нужна эта версия — https://github.com/jens-duttke/tslint-origin-ordered-imports-rule

Оригинал не умеет работать с адиасами.

**Comment by Uncleseneca** [comment]
@igorkamyshev  :ok_hand:
